import type { LucideIcon } from 'lucide-react'
import {
  AtSign,
  BadgeCheck,
  Building2,
  Calendar,
  CalendarDays,
  Camera,
  CircleUserRound,
  ExternalLink,
  Facebook,
  Gamepad2,
  Github,
  Globe2,
  Ghost,
  Image,
  Instagram,
  Linkedin,
  Link2,
  Mail,
  Map,
  MapPin,
  Medal,
  MessageCircle,
  MessagesSquare,
  Mic2,
  MousePointerClick,
  Music2,
  Palette,
  Phone,
  PlaySquare,
  Send,
  Shield,
  Sparkles,
  Star,
  Store,
  Text,
  Twitter,
  UserRound,
  Video,
  Youtube,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  user: UserRound,
  briefcase: BadgeCheck,
  building: Building2,
  medal: Medal,
  sparkles: Sparkles,
  mail: Mail,
  phone: Phone,
  globe: Globe2,
  link: Link2,
  'map-pin': MapPin,
  twitter: Twitter,
  instagram: Instagram,
  'at-sign': AtSign,
  linkedin: Linkedin,
  facebook: Facebook,
  youtube: Youtube,
  ghost: Ghost,
  music: Music2,
  twitch: PlaySquare,
  star: Star,
  github: Github,
  'message-circle': MessageCircle,
  shield: Shield,
  send: Send,
  gamepad: Gamepad2,
  messages: MessagesSquare,
  video: Video,
  calendar: Calendar,
  image: Image,
  store: Store,
  'calendar-days': CalendarDays,
  map: Map,
  text: Text,
  'mouse-pointer': MousePointerClick,
  camera: Camera,
  palette: Palette,
  'external-link': ExternalLink,
  'circle-user': CircleUserRound,
  microphone: Mic2,
}

export const getIcon = (key: string): LucideIcon => iconMap[key] ?? Link2
